name: Git Merge

on:
  push:
    branches:
      - staging

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Git Merge
        run: |
          git config user.name "Jenkins"
          git config user.email "platform-engineering@MYCOMPANY.CO.UK"
          git fetch origin staging
          git merge staging dev
          git push