name: Pre-Build Hook

on:
  push:
    branches:
      - '*'

jobs:
  preBuildHook:
    runs-on: ubuntu-latest

    steps:
      - name: Pre-Build Hook
        run: |
          echo "Running preBuildHook.sh"