name: Wait for Selenium Grid

on:
  push:
    branches:
      - '*'

jobs:
  waitForSeleniumGrid:
    runs-on: ubuntu-latest

    steps:
      - name: Wait for Selenium Grid
        run: |
          echo "Running ./selenium_hub_wait_ready.sh '$SELENIUM_HUB_URL' 60"