name: MegaLinter

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: MegaLinter
        run: |
          container('megalinter') {
            sh '/entrypoint.sh'
          }