name: Run Single Package Tests

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11

      - name: Run Single Package Tests
        run: ./mvnw test -DselenoidUrl='$SELENIUM_HUB_URL' -Dtest='${{ env.PACKAGE }}' -DthreadCount='$THREAD_COUNT'