name: SonarQube Scan

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11

      - name: SonarQube Scan
        run: ./mvnw clean org.sonarsource.scanner.maven:sonar-maven-plugin:3.9.1.2184:sonar