name: Deploy to Azure Storage

on:
  workflow_call:
    inputs:
      storage-account:
        required: true
        type: string
      source-path:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Upload to Azure Storage
        uses: Azure/azure-storage-blob-upload@v1
        with:
          source: ${{ inputs.source-path }}
          destination: ${{ inputs.storage-account }}
        env:
          AZURE_STORAGE_CONNECTION_STRING: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}