name: Notify Result

on:
  workflow_call:
    inputs:
      status:
        required: true
        type: string
      recipients:
        required: true
        type: string

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Notification
        run: echo "Sending ${{ inputs.status }} notification to ${{ inputs.recipients }}"