name: Run Jscrambler

on:
  workflow_call:
    inputs:
      jscrambler-access-key:
        required: true
        type: string
      jscrambler-secret-key:
        required: true
        type: string
      jscrambler-application-id:
        required: true
        type: string

jobs:
  jscrambler:
    runs-on: ubuntu-latest
    steps:
      - name: Install Jscrambler
        run: npm install jscrambler
      - name: Run Jscrambler
        run: |
          jscrambler -c jscrambler.json --access-key ${{ inputs.jscrambler-access-key }} --secret-key ${{ inputs.jscrambler-secret-key }} --application-id ${{ inputs.jscrambler-application-id }}