name: Docker Build Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Docker Build
        run: |
          docker build -t ${{ secrets.DOCKER_IMAGE }}:${{ github.sha }} .